services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  textconverterapp:
    image: textconverterapp
#    platform: linux/amd64
    build:
      context: .
      dockerfile: TextConverterApp/Dockerfile
    ports:
      - "8080:8080"
volumes:
  pgdata:
